const data = {
    products: [{
            name: 'Summer Shirt',
            slug: 'summer-shirt',
            category: 'Shirts',
            image: '/images/tshirt.jpg',
            price: 800,
            countInStock: 10,
            brand: 'Denim',
            rating: 4,
            numReviews: 10,
            description: 'Super cool Tshirt',
        },
        {
            name: 'Winter Shirt',
            slug: 'winter-shirt',
            category: 'Shirts',
            image: '/images/wshirt.png',
            price: 1200,
            countInStock: 10,
            brand: 'Denim',
            rating: 5,
            numReviews: 10,
            description: 'Super warm Tshirt',
        },
        {
            name: 'Summer Pant',
            slug: 'summer-pant',
            category: 'Pants',
            image: '/images/pant.jpg',
            price: 800,
            countInStock: 10,
            brand: 'Denim',
            rating: 4,
            numReviews: 10,
            description: 'Super cool pant',
        },
        {
            name: 'Winter Pant',
            slug: 'winter-pant',
            category: 'Pants',
            image: '/Images/wpant.jpg',
            price: 800,
            countInStock: 10,
            brand: 'Denim',
            rating: 4,
            numReviews: 10,
            description: 'Super warm pant',
        },
    ],
};

export default data;